# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: HappyLighting-py Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:    
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        architecture: 'x64'
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r LEDStripController/requirements.txt
    - name: Compile and generate exe
      run: |
        python -m pip install pyinstaller
        pyinstaller LEDStripController/pyhl.spec
   
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: PyHL - Windows Release generated
        path: dist/pyhl.exe
